workflows:
    react-native-ios:
        name: React Native iOS
        max_build_duration: 120
        environment:
          vars:
            XCODE_WORKSPACE: "NewExpensify.xcworkspace" # <-- Put the name of your Xcode workspace here
            XCODE_SCHEME: "NewExpensify" # <-- Put the name of your Xcode scheme here
            APP_ID: 1555555551
          node: 20.10.0
          npm: 10.2.3
          xcode: 16.3
        scripts:
            - name: Install npm dependencies
              script: |
                npm install --legacy-peer-deps
            - name: Install CocoaPods dependencies
              script: |
                cd ios && pod install
            - name: Build the .app
              script: | 
                xcode-project build \
                --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
                --scheme "$XCODE_SCHEME"
                -sdk iphonesimulator \
                -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=18.0' \
                -configuration Debug \
                CODE_SIGN_IDENTITY="" \
                CODE_SIGNING_REQUIRED=NO \
                CODE_SIGNING_ALLOWED=NO
        artifacts:
         - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
