workflows:
    react-native-ios:
        name: React Native iOS
        max_build_duration: 120
        cache:
          cache_paths:
            - $HOME/Library/Caches/CocoaPods
            - $CM_BUILD_DIR/node_modules
        scripts:
            - name: Install npm dependencies
              script: |
                npm install --legacy-peer-deps
            - name: Install CocoaPods dependencies
              script: |
                cd ios && pod install
            - name: Build unsigned .app for simulator
              script: | 
                --simulator
        artifacts:
          - build/ios/iphonesimulator/Runner.app
