workflows:
    react-native-ios:
        name: React Native iOS
        max_build_duration: 120
        environment:
          ios_signing:
            distribution_type: development
            bundle_identifier: io.cm.expensify.chat
          vars:
            XCODE_WORKSPACE: "NewExpensify.xcworkspace" # <-- Put the name of your Xcode workspace here
            XCODE_SCHEME: "NewExpensify" # <-- Put the name of your Xcode scheme here
            APP_ID: 1555555551
          node: 20.10.0
          npm: 10.2.3
          xcode: 16.3
        cache:
          cache_paths:
            - $HOME/Library/Caches/CocoaPods
            - $CM_BUILD_DIR/node_modules
        scripts:
            - name: Install npm dependencies
              script: |
                npm install --legacy-peer-deps
            - name: Install CocoaPods dependencies
              script: |
                cd ios && pod install
        artifacts:
         - build/ios/ipa/*.ipa
         - /tmp/xcodebuild_logs/*.log
         - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
         - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
